[phases.setup]
nixPkgs = ["php82", "nodejs_20"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader", "npm install", "npm run build"]

[phases.deploy]
cmds = ["php artisan migrate --force", "php artisan db:seed --class=PersonaSeeder --force", "php artisan serve --host 0.0.0.0 --port ${PORT:-8080}"]
